#!/usr/bin/env python
from __future__ import print_function

import roslib
roslib.load_manifest('my_package')
import sys
import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
from geometry_msgs.msg import Twist


class starter:

  def __init__(self):
    self.move_pub = rospy.Publisher("/cmd_vel",Twist)

    self.bridge = CvBridge()
    self.clock_sub = rospy.Subscriber("/rrbot/camera1/image_raw",Image,self.callback)
    
    self.driver_pub = rospy.Publisher("/rrbot/camera1/image_raw",Image,self.callback)


  def callback(self,data):
    try:
      cv_image = self.bridge.imgmsg_to_cv2(data, "bgr8")
    except CvBridgeError as e:
      print(e)